INSERT INTO public."Food" (name, type, "createdAt", "updatedAt") VALUES
('Silverside with Mustard Sauce', 'Meat', now(), now()),
('Pork Caserole', 'Meat', now(), now()),
('Curried Sausages', 'Meat', now(), now()),
('Lentil Loaf', 'Vegetable', now(), now()),
('Mini Pork Balls', 'Meat', now(), now()),
('Savoury Mince', 'Meat', now(), now()),
('Rice Crusted Quiche', 'Meat', now(), now()),
('Roast Beef', 'Meat', now(), now()),
('Roast Pork', 'Meat', now(), now()),
('Nutty Carrot Loaf', 'Meat', now(), now()),
('Crumb fish with lemon sauce', 'Meat', now(), now()),
('Wee Meat Balls', 'Meat', now(), now()),
('Spring Onion Tart', 'Meat', now(), now()),
('Pork & Apple Casserole', 'Meat', now(), now()),
('Lambs Fry & Bacon', 'Meat', now(), now()),
('Creamy Vegetable Bake', 'Meat', now(), now()),
('Chicken Red Wine Cassrole', 'Meat', now(), now()),
('Pork Schnitzel', 'Meat', now(), now()),
('Vegetable Quiche', 'Meat', now(), now()),
('Steak & Tomato Casserole', 'Meat', now(), now()),
('Chicken & Spinach Pie', 'Meat', now(), now()),
('Silverbeet Slice', 'Meat', now(), now()),
('Devil Sausages', 'Meat', now(), now()),
('Swiss Roll', 'Meat', now(), now()),
('Potato Bake', 'Meat', now(), now()),
('Baked Lemon Chicken', 'Meat', now(), now()),
('Cornish Pastie', 'Meat', now(), now()),
('Macaroni Cheese', 'Meat', now(), now()),
('Baked Hoki Fillets', 'Meat', now(), now()),
('Beef Cordon Bleu', 'Meat', now(), now()),
('Baked Filo Samosas', 'Meat', now(), now()),
('chilli bean mince', 'Meat', now(), now()),
('meatloaf', 'Meat', now(), now()),
('Pumpkin Lasagne', 'Meat', now(), now()),
('Apricot Chicken', 'Meat', now(), now()),
('Cheesy Leek & Potato Bake', 'Meat', now(), now()),
('Pork Riblets', 'Meat', now(), now()),
('Mushroom Risotto', 'Meat', now(), now()),
('Beef Swirls', 'Meat', now(), now()),
('Beef Schnitzel', 'Meat', now(), now()),
('Potato Lentil Salad', 'Meat', now(), now()),
('Roast Lamb & Mint Gravy', 'Meat', now(), now()),
('Frittata', 'Meat', now(), now()),
('Crumb Fish with Tartare Sauce', 'Meat', now(), now()),
('Meat Patties', 'Meat', now(), now()),
('Chop Suey Patties', 'Meat', now(), now()),
('Chicken Schnitzel', 'Meat', now(), now()),
('Pork Mince Balls', 'Meat', now(), now()),
('Chickpea & Lentil Curry', 'Meat', now(), now()),
('Savoury Meatloaf', 'Meat', now(), now()),
('Ham Steak with Pineapple', 'Meat', now(), now()),
('Curried Fish Cakes', 'Meat', now(), now()),
('Beefhot Pot', 'Meat', now(), now()),
('Roast Chicken with Gravy', 'Meat', now(), now()),
('Bombay Beans', 'Meat', now(), now()),
('Sweet & Sour Baked Fish', 'Meat', now(), now()),
('Bacon Egg Pie', 'Meat', now(), now()),
('Lentil Patties', 'Meat', now(), now()),
('Dressed Pie', 'Meat', now(), now()),
('Mini Rice Frittatas', 'Meat', now(), now()),
('Cottage Pie', 'Meat', now(), now()),
('Ham Potato & Cheese Pasties', 'Meat', now(), now()),
('Vegetarian Pizza', 'Meat', now(), now()),
('Sausages with Onion Gravy', 'Meat', now(), now()),
('Roast Vegetable Stew', 'Meat', now(), now()),
('Beef Stroganoff', 'Meat', now(), now()),
('Beef Hot Pot', 'Meat', now(), now()),
('Courgette Loaf', 'Meat', now(), now()),
('Broccoli Bake', 'Meat', now(), now()),
('Chicken Cordon Bleu', 'Meat', now(), now()),
('Potato Pie', 'Meat', now(), now()),
('Beef Olives', 'Meat', now(), now()),
('Zucchini Slice', 'Meat', now(), now()),
('Chicken, Bacon & Mushrooms in Gravy', 'Meat', now(), now()),
('Beef Lasagne Toppers', 'Meat', now(), now()),
('Asparagus & Egg Bake', 'Meat', now(), now()),
('Broccoli', 'Vegetable', now(), now()),
('Carrot', 'Vegetable', now(), now()),
('Scalloped Vegatables', 'Vegetable', now(), now()),
('Whole Baby Beans', 'Vegetable', now(), now()),
('Roasted Pumpkin', 'Vegetable', now(), now()),
('Asian Stir Fry', 'Vegetable', now(), now()),
('Cauliflower', 'Vegetable', now(), now()),
('Cabbage', 'Vegetable', now(), now()),
('Julienne Carrots', 'Vegetable', now(), now()),
('Peas', 'Vegetable', now(), now()),
('Kumara', 'Vegetable', now(), now()),
('Pumpkin', 'Vegetable', now(), now()),
('Stir Fry Vegetables', 'Vegetable', now(), now()),
('Roasted Kumara', 'Vegetable', now(), now()),
('Spinach', 'Vegetable', now(), now()),
('Green Beans', 'Vegetable', now(), now()),
('Mixed Vegetables', 'Vegetable', now(), now()),
('Carrot & Parsnips', 'Vegetable', now(), now()),
('Silverbeet', 'Vegetable', now(), now()),
('Roast Carrots', 'Vegetable', now(), now()),
('Cauliflower Cheese', 'Vegetable', now(), now()),
('Spanish Cream & Mandarins', 'Dessert', now(), now()),
('Vegetable', 'Soup', now(), now()),
('Leek & Potato', 'Vegetarian', now(), now()),
('Rice Crusted Quiche', 'Vegetarian', now(), now()),
('Spring Onion Tart', 'Vegetarian', now(), now()),
('Creamy Vegetable Bake', 'Vegetarian', now(), now()),
('Vegetable Quiche', 'Vegetarian', now(), now()),
('Silverbeet Slice', 'Vegetarian', now(), now()),
('Potato Bake', 'Vegetarian', now(), now()),
('Macaroni Cheese', 'Vegetarian', now(), now()),
('Baked Filo Samosas', 'Vegetarian', now(), now()),
('Pumpkin Lasagne', 'Vegetarian', now(), now()),
('Cheesy Leek & Potato Bake', 'Vegetarian', now(), now()),
('Mushroom Risotto', 'Vegetarian', now(), now()),
('Potato Lentil Salad', 'Vegetarian', now(), now()),
('Frittata', 'Vegetarian', now(), now()),
('cho', 'Vegetarian', now(), now()),
('Chick Pea Casserole', 'Vegetarian', now(), now()),
('Chickpea & Lentil Curry', 'Vegetarian', now(), now()),
('Curried Fish Cakes', 'Vegetarian', now(), now()),
('Spinach & Feta Crepes', 'Vegetarian', now(), now()),
('Bombay Beans', 'Vegetarian', now(), now()),
('Lentil Loaf', 'Vegetarian', now(), now()),
('Mini Rice Frittatas', 'Vegetarian', now(), now()),
('Roast Vegetable Stew', 'Vegetarian', now(), now()),
('Courgette Loaf', 'Vegetarian', now(), now()),
('Broccoli Bake', 'Vegetarian', now(), now()),
('Potato Pie', 'Vegetarian', now(), now()),
('Zucchini Slice', 'Vegetarian', now(), now()),
('Asparagus & Egg Bake', 'Vegetarian', now(), now()),
('Chicken & Noodle', 'Soup', now(), now()),
('Apple Sponge Crisp with Custard', 'Dessert', now(), now()),
('Creme of Mushroom', 'Soup', now(), now()),
('Fruit Trifle', 'Dessert', now(), now()),
('Pineapple Meringue Shortcake', 'Meat', now(), now()),
('Pineapple Meringue Shortcake', 'Dessert', now(), now()),
('Pumpkin & Carrot', 'Soup', now(), now()),
('Tomato', 'Soup', now(), now()),
('Sticky Date Pudding with Custard', 'Dessert', now(), now()),
('Chicken & Corn', 'Soup', now(), now()),
('Chocolate Sponge with Berry Coolie', 'Dessert', now(), now()),
('Leek & Potato', 'Soup', now(), now()),
('Asparagus', 'Soup', now(), now()),
('Queen Pudding', 'Dessert', now(), now()),
('Creme of Vegetable', 'Soup', now(), now()),
('Peach & Banana Upside Down Tart', 'Dessert', now(), now()),
('Pumpkin', 'Soup', now(), now()),
('Boysenberry Cheescake', 'Dessert', now(), now()),
('Apple & Blueberry Crumble with Custard', 'Dessert', now(), now()),
('Baked Rice', 'Dessert', now(), now()),
('Baked Raisin Pudding & Custard', 'Dessert', now(), now()),
('Mango & Passion Fruit Mousse', 'Dessert', now(), now()),
('Ambrosia', 'Dessert', now(), now()),
('Orange Banana Sponge & Custard', 'Dessert', now(), now()),
('Berry Trifle', 'Dessert', now(), now()),
('Steamed Ginger Pudding with Ginger Sauce', 'Dessert', now(), now()),
('Chocolate Instant Pudding with Fruit', 'Dessert', now(), now()),
('Lamington with Fruit Salad', 'Dessert', now(), now()),
('Pineapple Upside Down Cake', 'Dessert', now(), now()),
('Strawberry Instant Pudding with Fruit Salad', 'Dessert', now(), now()),
('Bread & Butter Pudding', 'Dessert', now(), now()),
('Boysenberry Shortcake', 'Dessert', now(), now()),
('Fruit Jelly', 'Dessert', now(), now()),
('Creamed Rice with Peaches', 'Dessert', now(), now()),
('Baked Rice and Mandarins', 'Dessert', now(), now()),
('Butterscotch & Banana Cream Pie', 'Dessert', now(), now()),
('Potatoes', 'Vegetable', now(), now()),
('Roast Potato', 'Vegetable', now(), now()),
('Wedges', 'Vegetable', now(), now()),
('Creamed Potatoes', 'Vegetable', now(), now()),
('Apricot Sponge', 'Dessert', now(), now()),
('Baked Custard Tart & Peaches', 'Dessert', now(), now()),
('Roast Pork with Apple Sauce', 'Meat', now(), now()),
('Roast Potatoes', 'Vegetable', now(), now()),
('Hungarian Goulash', 'Meat', now(), now()),
('Baked Sago', 'Dessert', now(), now()),
('Creme of Chicken', 'Soup', now(), now()),
('Mushroon', 'Soup', now(), now()),
('Mulligatawny', 'Soup', now(), now()),
('Chop Suey Patties', 'Vegetarian', now(), now()),
('Carrots', 'Vegetable', now(), now()),
('Lentil Patties', 'Vegetarian', now(), now()),
('Spilt Pea & Ham', 'Soup', now(), now()),
('Tomato & Rice', 'Soup', now(), now()),
('Pea & Ham', 'Soup', now(), now()),
('Kumara & Vegetable', 'Soup', now(), now()), 
('Corn', 'Vegetable', now(), now());