INSERT INTO public."Meats"(
	name, "createdAt", "updatedAt") VALUES
('Silverside with Mustard Sauce', now(), now()),
('Pork Caserole', now(), now()),
('Curried Sausages', now(), now()),
('Mini Pork Balls', now(), now()),
('Savoury Mince', now(), now()),
('Rice Crusted Quiche', now(), now()),
('Roast Beef', now(), now()),
('Roast Pork', now(), now()),
('Nutty Carrot Loaf', now(), now()),
('Crumb fish with lemon sauce', now(), now()),
('Wee Meat Balls', now(), now()),
('Spring Onion Tart', now(), now()),
('Pork & Apple Casserole', now(), now()),
('Lambs Fry & Bacon', now(), now()),
('Creamy Vegetable Bake', now(), now()),
('Chicken Red Wine Cassrole', now(), now()),
('Pork Schnitzel', now(), now()),
('Vegetable Quiche', now(), now()),
('Steak & Tomato Casserole', now(), now()),
('Chicken & Spinach Pie', now(), now()),
('Silverbeet Slice', now(), now()),
('Devil Sausages', now(), now()),
('Swiss Roll', now(), now()),
('Potato Bake', now(), now()),
('Baked Lemon Chicken', now(), now()),
('Cornish Pastie', now(), now()),
('Macaroni Cheese', now(), now()),
('Baked Hoki Fillets', now(), now()),
('Beef Cordon Bleu', now(), now()),
('Baked Filo Samosas', now(), now()),
('chilli bean mince', now(), now()),
('meatloaf', now(), now()),
('Pumpkin Lasagne', now(), now()),
('Apricot Chicken', now(), now()),
('Cheesy Leek & Potato Bake', now(), now()),
('Pork Riblets', now(), now()),
('Mushroom Risotto', now(), now()),
('Beef Swirls', now(), now()),
('Beef Schnitzel', now(), now()),
('Potato Lentil Salad', now(), now()),
('Roast Lamb & Mint Gravy', now(), now()),
('Frittata', now(), now()),
('Crumb Fish with Tartare Sauce', now(), now()),
('Meat Patties', now(), now()),
('Chop Suey Patties', now(), now()),
('Chicken Schnitzel', now(), now()),
('Pork Mince Balls', now(), now()),
('Chickpea & Lentil Curry', now(), now()),
('Savoury Meatloaf', now(), now()),
('Ham Steak with Pineapple', now(), now()),
('Curried Fish Cakes', now(), now()),
('Beefhot Pot', now(), now()),
('Roast Chicken with Gravy', now(), now()),
('Bombay Beans', now(), now()),
('Sweet & Sour Baked Fish', now(), now()),
('Bacon Egg Pie', now(), now()),
('Lentil Patties', now(), now()),
('Dressed Pie', now(), now()),
('Mini Rice Frittatas', now(), now()),
('Cottage Pie', now(), now()),
('Ham Potato & Cheese Pasties', now(), now()),
('Vegetarian Pizza', now(), now()),
('Sausages with Onion Gravy', now(), now()),
('Roast Vegetable Stew', now(), now()),
('Beef Stroganoff', now(), now()),
('Beef Hot Pot', now(), now()),
('Courgette Loaf', now(), now()),
('Broccoli Bake', now(), now()),
('Chicken Cordon Bleu', now(), now()),
('Potato Pie', now(), now()),
('Beef Olives', now(), now()),
('Zucchini Slice', now(), now()),
('Chicken, Bacon & Mushrooms in Gravy', now(), now()),
('Beef Lasagne Toppers', now(), now()),
('Asparagus & Egg Bake', now(), now());