INSERT INTO public."Vegetarians"(
	name, "createdAt", "updatedAt")
	VALUES ('Leek & Potato', now(), now()),
('Rice Crusted Quiche', now(), now()),
('Spring Onion Tart', now(), now()),
('Creamy Vegetable Bake', now(), now()),
('Vegetable Quiche', now(), now()),
('Silverbeet Slice', now(), now()),
('Potato Bake', now(), now()),
('Macaroni Cheese', now(), now()),
('Baked Filo Samosas', now(), now()),
('Pumpkin Lasagne', now(), now()),
('Cheesy Leek & Potato Bake', now(), now()),
('Mushroom Risotto', now(), now()),
('Potato Lentil Salad', now(), now()),
('Frittata', now(), now()),
('cho', now(), now()),
('Chick Pea Casserole', now(), now()),
('Chickpea & Lentil Curry', now(), now()),
('Curried Fish Cakes', now(), now()),
('Spinach & Feta Crepes', now(), now()),
('Bombay Beans', now(), now()),
('Lentil Loaf', now(), now()),
('Mini Rice Frittatas', now(), now()),
('Roast Vegetable Stew', now(), now()),
('Courgette Loaf', now(), now()),
('Broccoli Bake', now(), now()),
('Potato Pie', now(), now()),
('Zucchini Slice', now(), now()),
('Asparagus & Egg Bake', now(), now()),
('Chop Suey Patties', now(), now()),
('Lentil Patties', now(), now());