INSERT INTO Person_Title(person_title) VALUES('Mr')
INSERT INTO Person_Title(person_title) VALUES('Mrs')
INSERT INTO Person_Title(person_title) VALUES('Miss')

--INSERT INTO Phone_Number_Type('Home')
--INSERT INTO Phone_Number_Type('Work')
--INSERT INTO Phone_Number_Type('Mobile')

INSERT INTO Street_Type() VALUES('St')
INSERT INTO Street_Type(street_type) VALUES('Rd')
INSERT INTO Street_Type(street_type) VALUES('Dr')
INSERT INTO Street_Type(street_type) VALUES('Terrace')
INSERT INTO Street_Type(street_type) VALUES('Way')
INSERT INTO Street_Type(street_type) VALUES('Ave')
INSERT INTO Street_Type(street_type) VALUES('Ln')
INSERT INTO Street_Type(street_type) VALUES('Cres')
INSERT INTO Street_Type(street_type) VALUES('Pl')
INSERT INTO Street_Type(street_type) VALUES('Row')
INSERT INTO Street_Type(street_type) VALUES('Bank')

INSERT INTO Town_City(town_city) VALUES('Dunedin')
INSERT INTO Town_City(town_city) VALUES('Mosgiel')

INSERT INTO Driver_Position_Type(driver_position_type) VALUES('Staff')
INSERT INTO Driver_Position_Type(driver_position_type) VALUES('Volunteer')

INSERT INTO Postcode(postcode) VALUES('9010')
INSERT INTO Postcode(postcode) VALUES('9011')
INSERT INTO Postcode(postcode) VALUES('9012')
INSERT INTO Postcode(postcode) VALUES('9013')
INSERT INTO Postcode(postcode) VALUES('9014')
INSERT INTO Postcode(postcode) VALUES('9016')
INSERT INTO Postcode(postcode) VALUES('9018')
INSERT INTO Postcode(postcode) VALUES('9022')
INSERT INTO Postcode(postcode) VALUES('9076')
INSERT INTO Postcode(postcode) VALUES('9077')

INSERT INTO Ingredient_Type(ingredient_type) VALUES('Dessert')
INSERT INTO Ingredient_Type(ingredient_type) VALUES('Fruit')
INSERT INTO Ingredient_Type(ingredient_type) VALUES('Meat')
INSERT INTO Ingredient_Type(ingredient_type) VALUES('Soup')
INSERT INTO Ingredient_Type(ingredient_type) VALUES('Vegetable')
INSERT INTO Ingredient_Type(ingredient_type) VALUES('Sandwich')

INSERT INTO Meal_Option_Type(meal_option_type) VALUES('Gluten free')
INSERT INTO Meal_Option_Type(meal_option_type) VALUES('Extra vegetables')
INSERT INTO Meal_Option_Type(meal_option_type) VALUES('Cut meat')
INSERT INTO Meal_Option_Type(meal_option_type) VALUES('Diabetic')
INSERT INTO Meal_Option_Type(meal_option_type) VALUES('Puree')
INSERT INTO Meal_Option_Type(meal_option_type) VALUES('Vegetarian')

INSERT INTO Day_Period(day_period) VALUES('Breakfast')
INSERT INTO Day_Period(day_period) VALUES('Lunch')
INSERT INTO Day_Period(day_period) VALUES('Dinner')

INSERT INTO Day_Of_Week(day_of_week) VALUES('Monday')
INSERT INTO Day_Of_Week(day_of_week) VALUES('Tuesday')
INSERT INTO Day_Of_Week(day_of_week) VALUES('Wednesday')
INSERT INTO Day_Of_Week(day_of_week) VALUES('Thursday')
INSERT INTO Day_Of_Week(day_of_week) VALUES('Friday')
INSERT INTO Day_Of_Week(day_of_week) VALUES('Saturday')
INSERT INTO Day_Of_Week(day_of_week) VALUES('Sunday')


